# Generated by Django 4.0 on 2023-02-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='friend',
            field=models.ManyToManyField(to='webapp.Friends'),
        ),
    ]
