# Generated by Django 4.0 on 2023-02-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_friends_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='friend',
            field=models.ManyToManyField(to='webapp.AppUser'),
        ),
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
