# Generated by Django 3.2 on 2023-03-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_appuser_friend_delete_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='friend',
            field=models.ManyToManyField(related_name='_webapp_appuser_friend_+', to='webapp.AppUser'),
        ),
        migrations.AlterField(
            model_name='images',
            name='description',
            field=models.ImageField(upload_to=''),
        ),
    ]
